channels:
- conda-forge
dependencies:
- python=3.10.11
- pip<=24.1
- pip:
  - mlflow==2.14.1
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==24.1
  - psutil==6.0.0
  - pyyaml==6.0.1
  - scikit-learn==1.5.0
  - scipy==1.13.1
name: mlflow-env
