name: CI_TESTS
on:
  pull_request:
    branches:
      - main
    paths:
      - '06-best-practices/code-practice/**'
env:
  AWS_DEFAULT_REGION: 'eu-west-1'
  #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: '06-best-practices/code-practice'
        run: pip install pipenv && pipenv install --dev

      - name: Run Quality tests
        working-directory: '06-best-practices/code-practice'
        run: make quality_checks
