name: Test-PR
on:
  pull_request:
    branches:
      - 'develop'
    paths:
      - '06-best-practices/code/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies, Lint with black, & run tests with Pytest
        working-directory: "06-best-practices/code"
        run: |
          pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          make setup
          make quality_checks

      - name: Run Unit tests
        working-directory: "06-best-practices/code"
        run: |
          make test

      - name: Integration Test
        working-directory: '06-best-practices/code/integraton-test'
        run: |
          . run.sh

  tf-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-west-1"

      - uses: hashicorp/setup-terraform@v2

      - name: TF plan
        id: plan
        working-directory: '06-best-practices/code/infrastructure'
        run: |
          terraform init && terraform plan -var-file=vars/prod.tfvars
