name: Test-PR
on:
  pull_request:
    branches:
      - 'develop'
    paths:
      - '06-best-practices/code/**'

jobs:
  unit-test:
    name: Run Unit tests
    runs-on: ubuntu-latest
    working-directory: "06-best-practices/code"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          make setup
      - name: Lint with black
        run: |
          make quality_checks
      - name: Test with pytest
        run: |
          make test

    integration-test:
      name: Run Integration tests
      runs-on: ubuntu-latest
#      strategy:
#        matrix:
#          include:
#            - dir:
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-1'
      steps:
        - uses: actions/checkout@v2

        - name: Set up Python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_DEFAULT_REGION }}

        - name: Setup
          working-directory: '06-best-practices/code'
          run: |
            make setup

        - name: Integration Test
          working-directory: '06-best-practices/code/integraton-test'
          run: |
            . run.sh

